version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./imgs:/app/imgs
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5435:5432"
