[tasks.redo]
description = "Redoes the database downloading the dataset and formatting/parsing the data."
env = { "RUST_LOG" = "info", "REDO" = "1" }
command = "cargo"
args = ["run"]

[tasks.run]
description = "Reads the Postgres database and outputs the 10 words with highest and lowest frequencies in the poems."
command = "cargo"
args = ["run"]

[tasks.export]
description = "Runs `pg2parquet` to export the Postgres database to a parquet file."
install_crate = "pg2parquet"
command = "pg2parquet"
args = [
    "export",
    "--user",
    "le-moski",
    "--host",
    "/var/run/postgresql/",
    "--dbname",
    "poems",
    "--output-file",
    "poems.parquet",
    "-t",
    "poems",
]
